CREATE CONSTRAINT IF NOT EXISTS FOR (d:Developer) REQUIRE d.username IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (r:Repository) REQUIRE r.fullName IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (t:Technology) REQUIRE t.normalizedName IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (t:Topic) REQUIRE t.normalizedName IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (o:Organization) REQUIRE o.login IS UNIQUE;
